import sqlite3
import tkinter as tk
def certificate():
    studentregistrionNO=Entry_studentregistrionNO.get()
    studentfullname=Entry_studentfullname.get()
    studentstartdate=Entry_studentstartdate.get()
    studentenddate=Entry_studentenddate.get()
    coursename=Entry_coursename.get()
    studentgrade=Entry_studentgrade.get()
    connect=sqlite3.connect("addcertificate.db")
    cursor=connect.cursor()
    cursor.execute('''create table if not exists degree(studentregistrionNO integer,studentfullname text,studentstartdate integer,studentenddate integer,coursename text,studentgrade integer_notnull)''')
    cursor.execute('''insert into degree(studentregistrionNO,studentfullname,studentstartdate,studentenddate ,coursename,studentgrade)values(?,?,?,?,?,?)''',(studentregistrionNO,studentfullname,studentstartdate,studentenddate ,coursename,studentgrade))
    connect.commit()
    connect.close()
#TKINTER
root=tk.Tk()
label_studentregistrionNO=tk.Label(root,text="STUDENTS REGISTRION NO.")
label_studentregistrionNO.grid(row=0,column=1)
Entry_studentregistrionNO=tk.Entry(root)
Entry_studentregistrionNO.grid(row=0,column=2)
Label_studentfullname=tk.Label(root,text="STUDENT FULL NAME")
Label_studentfullname.grid(row=1,column=1)
Entry_studentfullname=tk.Entry(root)
Entry_studentfullname.grid(row=1,column=2)
Label_studentstartdate=tk.Label(root,text="STUDENT START DATE")
Label_studentstartdate.grid(row=2,column=1)
Entry_studentstartdate=tk.Entry(root)
Entry_studentstartdate.grid(row=2,column=2)
Label_studentenddate=tk.Label(root,text="STUDENT END DATE")
Label_studentenddate.grid(row=3,column=1)
Entry_studentenddate=tk.Entry(root)
Entry_studentenddate.grid(row=3,column=2)
Label_coursename=tk.Label(root,text="COURSE NAME")
Label_coursename.grid(row=4,column=1)
Entry_coursename=tk.Entry(root)
Entry_coursename.grid(row=4,column=2)
Label_studentgrade=tk.Label(root,text="STUDENT GRADE")
Label_studentgrade.grid(row=5,column=1)
Entry_studentgrade=tk.Entry(root)
Entry_studentgrade.grid(row=5,column=2)
submit_Button=tk.Button(root,text="SUBMIT BUTTON",command=certificate)
submit_Button.grid(row=6,column=2)
root.mainloop()

