import sqlite3
import tkinter as tk
def employe():
    Title=Entry_Title.get()
    fullname=Entry_fullname.get()
    workexperince=Entry_workexperince.get()
    studentenddate=Entry_studentenddate.get()
    company=Entry_company.get()
    gender=Entry_gender.get()
    DOB=Entry_DOB.get()
    salary=Entry_salary.get()
    bloodgroup=Entry_bloodgroup.get()
    address=Entry_address.get()
    city=Entry_city.get()
    pincode=Entry_pincode.get()
    connect=sqlite3.connect("addemploye.db")
    cursor=connect.cursor()
    cursor.execute('''create table if not exists work(Title text,fullname text,workexperince text,studentenddate integer,company text,gender text,DOB integer,salary integer, bloodgroup text,address text,city text,pincode integer_notnull)''')
    cursor.execute('''insert into work(Title,fullname,workexperince,studentenddate,company,gender,DOB,salary,bloodgroup,address,city,pincode)values(?,?,?,?,?,?,?,?,?,?,?,?)''',(Title,fullname,workexperince,studentenddate,company,gender,DOB,salary,bloodgroup,address,city,pincode))
    connect.commit()
    connect.close()
#TKINTER
root=tk.Tk()
label_Title=tk.Label(root,text="TITLE")
label_Title.grid(row=0,column=1)
Entry_Title=tk.Entry(root)
Entry_Title.grid(row=0,column=2)
Label_fullname=tk.Label(root,text="FULL NAME")
Label_fullname.grid(row=1,column=1)
Entry_fullname=tk.Entry(root)
Entry_fullname.grid(row=1,column=2)
Label_workexperince=tk.Label(root,text="WORK EXPERINCE")
Label_workexperince.grid(row=2,column=1)
Entry_workexperince=tk.Entry(root)
Entry_workexperince.grid(row=2,column=2)
Label_studentenddate=tk.Label(root,text="STUDENT END DATE")
Label_studentenddate.grid(row=3,column=1)
Entry_studentenddate=tk.Entry(root)
Entry_studentenddate.grid(row=3,column=2)
Label_company=tk.Label(root,text="COMPANY")
Label_company.grid(row=4,column=1)
Entry_company=tk.Entry(root)
Entry_company.grid(row=4,column=2)
Label_gender=tk.Label(root,text="GENDER")
Label_gender.grid(row=5,column=1)
Entry_gender=tk.Entry(root)
Entry_gender.grid(row=5,column=2)
Label_DOB=tk.Label(root,text="D.O.B")
Label_DOB.grid(row=6,column=1)
Entry_DOB=tk.Entry(root)
Entry_DOB.grid(row=6,column=2)
Label_salary=tk.Label(root,text="SALARY")
Label_salary.grid(row=7,column=1)
Entry_salary=tk.Entry(root)
Entry_salary.grid(row=7,column=2)
Label_bloodgroup=tk.Label(root,text="BLOOD GROUP")
Label_bloodgroup.grid(row=8,column=1)
Entry_bloodgroup=tk.Entry(root)
Entry_bloodgroup.grid(row=8,column=2)
Label_address=tk.Label(root,text="ADDRESS")
Label_address.grid(row=9,column=1)
Entry_address=tk.Entry(root)
Entry_address.grid(row=9,column=2)
Label_city=tk.Label(root,text="CITY")
Label_city.grid(row=10,column=1)
Entry_city=tk.Entry(root)
Entry_city.grid(row=10,column=2)
Label_pincode=tk.Label(root,text="PINCODE")
Label_pincode.grid(row=11,column=1)
Entry_pincode=tk.Entry(root)
Entry_pincode.grid(row=11,column=2)
submit_Button=tk.Button(root,text="SUBMIT BUTTON",command=employe)
submit_Button.grid(row=13,column=2)
root.mainloop()

